services:
  cloudflare-bypass:
    image: ghcr.io/sarperavci/cloudflarebypassforscraping:latest
    container_name: cloudflare-bypass
    ports:
      - "8005:8005"
    environment:
      - WORKERS=3
    deploy:
      resources:
        limits:
          memory: 4G
          cpus: "0.5"
    shm_size: 2g
    restart: unless-stopped
